# Tokens
id = [a-zA-Z][a-zA-Z0-9]*
int = [0-9]+
imp_id = ?id
unit = "()"

# Using extended BNF notation
# The following is the CFG for the implicit parameters coeffect system

<prog> ::= <decl>* ';' <expr> .

# Declarations
<decl> ::= <fun_decl>
         | <val_decl> .

<fun_decl> ::= 'fun' id <param>+ <imps>? (':' <type>)? '=' <expr> .
<param> ::= '(' id ':' <type> ')'

<val_decl> ::= 'val' id (':' <type>)? '=' <expr> .

# Implicit Parameters
<imps> ::= '{' <imps_inner> '}' .
<imps_inner> ::= <imp> (',' <imp>)* | . 
<imp>  ::= imp_id ':' <type> .

# Types
<type> ::= <base_type> | <base_type> <imps>? '->' <type> .

<base_type> ::= 'int' 
              | 'unit' 
              | '(' <type> ')' .

# Expressions  
<expr> ::= <abs> .

<abs> ::= '\\' <param> <imps>? '->' <abs> | <letdyn> .

<letdyn> ::= 'letdyn' imp_id '=' <add> 'in' <add> | <add> .

<add> ::= <app> ( '+' <app> )* .

<app> ::= <simple>+

<simple> :: id 
          | int
          | imp_id
          | unit
          | "(" <expr> ")" .